#!/usr/bin/env bash

# Helper script to set up Verificarlo CI on the current branch

# Get name of both current and new CI branch
dev_branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')
ci_branch="vfc_ci_${dev_branch}"


# Create test workflow on the dev branch
echo "Creating Verificarlo test workflow on the current branch..."
mkdir -p .github/workflows
# We assume the script is included in the repo for now
# (we'll probably want to remove "./" if the script ends up being integrated
# in Verificarlo and becomes available system-wide)
python setup_test_workflow.py $dev_branch $ci_branch

git add .github/workflows/vfc_test_workflow.yml
git commit -m "[auto] Set up Verificarlo CI on this branch"
echo "Pushing changes to remote : you might have to enter your Github credentials..."
git push origin $dev_branch


# Populate the CI branch
echo "Populating the CI branch..."

if [ -f "README.md" ]; then # Backup original readme if there is one
    mv README.md README.md.tmp
fi
# We assume the script is included in the repo for now
# (we'll probably want to remove "./" if the script ends up being integrated
# in Verificarlo and becomes available system-wide)
python setup_ci_readme.py $dev_branch $ci_branch

# Create the repertory that will contain the vfcrun files
mkdir vfcruns

# Create Verificarlo CI branch
echo "Creating the Verificarlo CI branch (${ci_branch})..."
git checkout --orphan $ci_branch
git rm --cached -r -f .
git add README.md vfcruns
git commit -m "[auto] Create the Verificarlo CI branch for ${dev_branch}"
echo "Pushing changes to remote : you might have to enter your Github credentials..."
git push -u origin $ci_branch


# Cleanup and print termination message
rm README.md
rm -rf vfcruns
if [ -f "README.md.tmp" ]; then
    mv README.md.tmp README.md
fi
git add .
git checkout $dev_branch

echo
echo
echo "The Verificarlo CI workflow has been set up on this branch !"
echo "When pushing on ${dev_branch}, the ${ci_branch} branch will be \
automatically updated with your Verificarlo test results (make sure you have \
set a vfc_tests_config.json on this branch)."
echo
echo
