# This workflow will be executed when {{dev_branch}} is updated:
# it will run the configured tests and upload the results on vfc_ci_master.

image: verificarlo/verificarlo


stages:
  - run_tests


run_tests:
  stage: run_tests

  before_script:
  - git remote set-url origin https://{{username}}:${CI_PUSH_TOKEN}@{{remote_url}}.git
  - git config --global user.email "{{email}}"
  - git config --global user.name "{{username}}"

  script:
  - pip install numpy scipy pandas bokeh jinja2 tables GitPython
  - apt update
  - apt install wget
  - wget https://raw.githubusercontent.com/verificarlo/significantdigits/main/sigdigits.py -P /usr/local/lib/python3.8/dist-packages

  - ./vfc_ci test -g -r
  - git_hash=$(git rev-parse --short "$CI_COMMIT_SHA")
  - git fetch --all
  - git checkout -b {{ci_branch}} origin/{{ci_branch}}
  - mkdir -p vfcruns
  - mv *.vfcrun.hd5 vfcruns
  - git add vfcruns/*
  - git commit -m "[auto] New test results for commit ${git_hash}"
  - git push

  rules:
    - if: '$CI_COMMIT_BRANCH == "{{dev_branch}}"'

  artifacts:
    paths:
    - "*.vfcraw.hd5"
