# This workflow will be executed when {{dev_branch}} is updated:
# it will run the configured tests and upload the results on {{ci_branch}}.

name: "Verificarlo CI ({{dev_branch}})"

on:
  # Triggers the workflow when {{dev_branch}} is updated
  push:
    branches: [ {{dev_branch}} ]

  workflow_dispatch:


jobs:
  run_verificarlo_tests:
    runs-on: ubuntu-latest
    container: verificarlo/verificarlo

    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0

      # We will probably drop these installations when integrating CI into
      # Verificarlo
      - name: Install Python requirements
        run: |
          pip install numpy scipy pandas bokeh jinja2 tables GitPython

          apt install wget
          wget https://raw.githubusercontent.com/verificarlo/significantdigits/main/sigdigits.py -P /usr/local/lib/python3.8/dist-packages

      - name: Run tests
        # We assume the script is included in the repo for now
        # (we'll probably want to remove "./" if the script ends up being integrated
        # in Verificarlo and becomes available system-wide)
        run: ./vfc_ci test -g -r

      - name: Commit test results
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git checkout {{ci_branch}}
          mkdir -p vfcruns
          mv *.vfcrun.hd5 vfcruns
          git add vfcruns/*
          git commit -m "[auto] New test results for commit ${git_hash}"
          git push

      - name: Upload raw results as artifacts
        uses: actions/upload-artifact@v2
        with:
          {% raw %}name: ${{github.sha}}.vfcraw{% endraw %}
          path: ./*.vfcraw.hd5
