# This workflow will be executed when master is updated:
# it will run the configured tests and upload the results on vfc_ci_master.

name: "Verificarlo CI (master)"

on:
  # Triggers the workflow when master is updated
  push:
    branches: [ master ]

  workflow_dispatch:


jobs:
  run_verificarlo_tests:
    runs-on: ubuntu-latest
    container: verificarlo/verificarlo

    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0

      # We will probably drop these installations when integrating CI into
      # Verificarlo
      - name: Install Python requirements
        run: |
          pip install numpy scipy pandas bokeh jinja2 tables GitPython

          git submodule init
          git submodule update

          cp vfc_hashmap.h  /usr/local/include
          cp vfc_probes.c /usr/local/include/vfc_probes.h
          cp vfc_ci /usr/local/lib/python3.8/site-packages/verificarlo
          cp -r ci /usr/local/lib/python3.8/site-packages/verificarlo
          cp sigdigits/sigdigits.py /usr/local/lib/python3.8/site-packages/verificarlo
          cp vfc_ci /usr/local/bin

          clang -c -fPIC vfc_hashmap.c vfc_probes.c
          clang vfc_probes.o vfc_hashmap.o -shared -o libvfc_probes.so
          cp *.so /usr/local/lib
          ldconfig


      - name: Run tests
        run: vfc_ci test -g -r

      - name: Commit test results
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git checkout vfc_ci_master
          mkdir -p vfcruns
          mv *.vfcrun.h5 vfcruns
          git add vfcruns/*
          git commit -m "[auto] New test results for commit ${git_hash}"
          git push

      - name: Upload raw results as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{github.sha}}.vfcraw
          path: ./*.vfcraw.h5
