# This workflow will be executed when master is updated:
# it will generate the new Verificarlo report and commit it to vfc_ci_master.

name: "Generate Verificarlo report"

# Controls when the action will run.
on:
  # Triggers the workflow when master is updated
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  gen-report:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Install requirements
        run: sudo pip install numpy pandas bokeh jinja2

      # The dummy test is used for now
      - name: Run tests
        run: python dummy_test.py

      # The dummy report is used for now
      - name: Generate report
        run: python gen_dummy_report.py

      - name: Commit test results and report
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git checkout vfc_ci_master
          git add *.vfcrun.json report.html
          git commit -m "[auto] New test results and updated report for commit ${git_hash}"
          git push