# This workflow will be executed when master is updated:
# it will run the configured tests and upload the results on vfc_ci_master.

name: "Verificarlo CI(master)"

on:
  # Triggers the workflow when master is updated
  push:
    branches: [ master ]

  workflow_dispatch:


jobs:
  gen-report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Install Python requirements
        run: sudo pip install numpy pandas bokeh jinja2 tables GitPython

      - name: Install Verificarlo
        run: |
          git clone https://github.com/verificarlo/verificarlo
          cd verificarlo
          sudo apt-get install libmpfr-dev clang-7 flang-7 llvm-7-dev llvm-11-dev llvm-11-tools \
          gcc-7 autoconf automake build-essential python3 python3-numpy python3-pip
          ./autogen.sh
          ./configure --with-flang CC=gcc-7 CXX=g++-7
          make
          sudo make install
          cd ..
          rm -rf verificarlo

      # For now, we assume the script is included in the repo
      # (we'll probably want to remove "./" if the script ends up being integrated
      # in Verificarlo and becomes available system-wide)
      - name: Run tests
        run: ./vfc_run_tests -g

      - name: Commit test results
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git checkout vfc_ci_master
          mkdir -p vfcruns
          mv *.vfcrun.hd5 vfcruns
          git add vfcruns/*
          git commit -m "[auto] New test results for commit ${git_hash}"
          git push
